### ISSUE TITLE
java.lang.AssertionError: Unknown channel type for update: 0

### ISSUE THREAD

**Issue by JONTTM** [dyon-b/discordfabriclink#4]
Not sure what is broken or what is causing this. The bot still seems to work after this error.

config/discordfabriclink.json5
```
{ 
	// Bot token
	"discordBotToken": "NTc4MzY5ODM1MDQ2NTM1MTcw.XNym4g.kcNwfqPdLB6AzBBaRogR1wHM6I0",
	// Chatting channel ID
	"chatChannelId": "655996452312711169",
	// The message keys that will be sent to the public chat
	"publicKeys": [ 
		"chat.type.text"
	],
	// Send admin commands
	"sendAdminCommands": false,
	// Log the keys
	"logKeys": false,
	// Webhook name
	"webhookName": "Discord Fabric Link",
	// The format to use in the Minecraft chat
	"minecraftChatFormat": "<%s> %s",
	// UUID face API
	"uuidFaceApi": "https://crafatar.com/avatars/%s?overlay&size=128"
}
```

```
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: java.lang.AssertionError: Unknown channel type for update: 0
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.common.store.legacy.LegacyStoreLayout.onChannelUpdate(LegacyStoreLayout.java:395)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.common.store.Store.lambda$gatewayDataUpdaterToMapper$33(Store.java:180)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.common.store.api.ActionMapper$Builder.lambda$map$0(ActionMapper.java:111)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.common.store.api.ActionMapper.lambda$null$1(ActionMapper.java:86)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.common.store.Store.lambda$execute$59(Store.java:245)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at java.util.Optional.map(Optional.java:215)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.common.store.Store.execute(Store.java:245)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.gateway.state.DispatchStoreLayer.lambda$store$9(DispatchStoreLayer.java:142)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:178)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:360)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.MonoSingle$SingleSubscriber.request(MonoSingle.java:101)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2154)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.MonoSingle$SingleSubscriber.onSubscribe(MonoSingle.java:121)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxStream.subscribe(FluxStream.java:71)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:425)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:387)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onNext(FluxTakeUntilOther.java:216)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:478)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:286)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:252)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.gateway.PayloadHandlers.handleDispatch(PayloadHandlers.java:80)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.gateway.PayloadHandlers.lambda$handle$0(PayloadHandlers.java:69)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:425)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:542)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:1006)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discord4j.gateway.payload.JacksonPayloadReader.lambda$read$1(JacksonPayloadReader.java:57)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:425)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:478)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:286)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:252)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:184)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:711)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:587)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:993)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1766)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.checkTerminated(FluxWindowPredicate.java:755)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:649)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:735)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onComplete(FluxWindowPredicate.java:801)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:235)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:265)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:371)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:381)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:686)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.netty.http.client.WebsocketClientOperations.onInboundNext(WebsocketClientOperations.java:157)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at discordfabriclink.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[02:15:11] [reactor-http-nio-4/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JONTTM** [comment]
I removed it for now because no one is playing on the server, but when 1.17 comes out I will look for another option.
